server:
  port: 8101

es:
  abelfgdeveloper:
    api:
      title: Customers API
      description: API para la gestion de los dueños y sus mascotas
      version: @project.version@
  
spring:
  application:
    name: pet-clinic-customers-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pet_clinic?currentSchema=customers
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    installed-by: ${spring.application.name}
  jackson:
    default-property-inclusion: non-null
    
